#CreateFileList.pl -run 15 -type 27 -pileup 5 DST_CALO_CLUSTER DST_CALO_G4HIT DST_TRACKS DST_TRACKSEEDS DST_TRKR_CLUSTER DST_TRKR_HIT G4Hits DST_TRKR_G4HIT DST_TRUTH DST_TRUTH_RECO -n 100000
CreateFileList.pl -run 15 -type 27 -pileup 5 DST_CALO_CLUSTER DST_CALO_G4HIT DST_TRACKS DST_TRACKSEEDS DST_TRKR_CLUSTER DST_TRKR_HIT G4Hits DST_TRKR_G4HIT DST_TRUTH -n 100000
